name: xmos-ai-tools-build-and-test

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Provide a valid branch or commit hash"
        required: true
  pull_request:

# Save the tag version in an environment variable
# The pretend version is used for the wheel as the
# tag version might be a branch name or commit hash
env:
  TAG_VERSION: ${{ github.event.inputs.version }}
  PRETEND_VERSION: 0.1.1
  BAZEL_CACHE_URL: https://storage.googleapis.com/bazel_remote_cache_0/gh_actions

jobs:
  macos-release-wheel:
    name: Build and test release wheels for macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ env.TAG_VERSION }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - uses: google-github-actions/auth@v0
        continue-on-error: true
        with:
          credentials_json: ${{ secrets.BAZEL_REMOTE_CACHE_JSON_KEY }}
      - name: Build setup
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ env.PRETEND_VERSION }}
        shell: bash
        run: |
          ls -alrt
          git status
          
          cd $GITHUB_WORKSPACE/third_party/lib_tflite_micro
          ls -alrt
          git status
          
          cd $GITHUB_WORKSPACE/third_party/lib_nn
          ls -alrt
          git status

